import { api, z, postgres, anthropic } from "@superblocksteam/sdk-api";
import { runPipelineCore } from "./pipeline-core.js";

// ---------------------------------------------------------------------------
// Background Pipeline Runner (Safety Net)
//
// Design:
//   - Intended to run on a 5-minute schedule (external cron or manual trigger)
//   - Finds module_runs in 'running' status where triggered_at > 6 minutes old
//     (meaning no client tab or previous invocation is actively driving it)
//   - Picks ONE stale run and re-invokes the shared pipeline core
//   - Uses the existing runId so it resumes from checkpoints — zero data loss
//
// Why one run per invocation?
//   - Each pipeline pass can consume up to 4m10s of the 5-min platform limit
//   - Processing multiple runs sequentially would exceed the timeout
//   - External scheduler calls this every 5 minutes anyway
//
// Coexistence with client poll loop:
//   - Client refreshes triggered_at per batch (heartbeat)
//   - So actively-driven runs always have triggered_at < 6 min and are skipped
//   - If client disconnects, triggered_at goes stale → this picks it up next cycle
//
// On completion:
//   - Saves to module_outputs (same INSERT the client would do via SaveModuleResult)
//   - Since no client is present, the background runner is responsible for persisting
//     the final report so the UI can display it later
// ---------------------------------------------------------------------------

const IC_DILIGENCE_DB = "ba09e2b9-2715-4460-8131-896f50b0c414";
const ANTHROPIC_ID = "8ccd43c8-5340-4ae2-8eee-7cbb3896df53";

const STALENESS_THRESHOLD_MINUTES = 6;

const StaleRunSchema = z.object({
  id: z.string(),
  deal_id: z.string(),
  module_id: z.string(),
});

export default api({
  name: "ResumeStalePipelines",
  description: "Background safety net: finds stale running pipelines and resumes them",

  integrations: {
    db: postgres(IC_DILIGENCE_DB),
    ai: anthropic(ANTHROPIC_ID),
  },

  input: z.object({}),

  output: z.object({
    found: z.number(),
    resumed: z.string().nullable(),
    outcome: z.string(),
  }),

  async run(ctx) {
    // Find stale runs: status='running' and triggered_at older than threshold
    const staleRuns = await ctx.integrations.db.query(
      `SELECT id, deal_id, module_id
       FROM module_runs
       WHERE status = 'running'::module_status
         AND triggered_at < now() - interval '${STALENESS_THRESHOLD_MINUTES} minutes'
       ORDER BY triggered_at ASC
       LIMIT 5`,
      StaleRunSchema,
      [],
      { label: "Find stale running pipelines" }
    );

    if (staleRuns.length === 0) {
      return { found: 0, resumed: null, outcome: "No stale runs found" };
    }

    // Pick the oldest stale run to resume
    const target = staleRuns[0];

    // Refresh triggered_at immediately to prevent other invocations from picking the same run
    await ctx.integrations.db.execute(
      `UPDATE module_runs SET triggered_at = now() WHERE id = $1`,
      [target.id],
      { label: "Claim stale run (refresh triggered_at)" }
    );

    // Call the shared pipeline core — exact same code path as RunModulePipeline
    const result = await runPipelineCore(ctx, {
      dealId: target.deal_id,
      moduleId: target.module_id,
      runId: target.id,
      useOpus: false, // Background runner uses Sonnet for cost efficiency
      numericReport: null, // Not available server-side; numeric data was merged during initial analysis
    });

    // If the pipeline completed, persist the output to module_outputs
    // (since no client is present to call SaveModuleResult)
    if (result.status === "completed" && result.result) {
      // Build a simple full-report markdown from findings
      const findingsMarkdown = result.result.findings.map((f: any) => {
        const sev = f.severity ? `[${String(f.severity).toUpperCase()}]` : "";
        return `### ${sev} ${f.title}\n\n${f.detail || f.full_analysis || ""}`;
      }).join("\n\n---\n\n");

      const fullReport = `# ${target.module_id.replace(/_/g, " ").replace(/\b\w/g, (c: string) => c.toUpperCase())}\n\n## Executive Summary\n\n${result.result.executiveHeader}\n\n## Findings\n\n${findingsMarkdown}\n\n---\n*Generated by background pipeline runner.*`;

      // Check if a row already exists (no unique index available due to table ownership)
      const existing = await ctx.integrations.db.query(
        `SELECT id FROM module_outputs WHERE module_run_id = $1 LIMIT 1`,
        z.object({ id: z.string() }),
        [result.runId],
        { label: "Check existing module_output" }
      );

      if (existing.length > 0) {
        // Update existing row
        await ctx.integrations.db.execute(
          `UPDATE module_outputs
           SET executive_header = $2, findings = $3::jsonb, full_report_markdown = $4
           WHERE module_run_id = $1`,
          [
            result.runId,
            result.result.executiveHeader,
            JSON.stringify(result.result.findings),
            fullReport,
          ],
          { label: "Update module output (background completion)" }
        );
      } else {
        // Insert new row
        await ctx.integrations.db.execute(
          `INSERT INTO module_outputs (module_run_id, executive_header, findings, full_report_markdown)
           VALUES ($1, $2, $3::jsonb, $4)`,
          [
            result.runId,
            result.result.executiveHeader,
            JSON.stringify(result.result.findings),
            fullReport,
          ],
          { label: "Save module output (background completion)" }
        );
      }

      // Bump deal updated_at
      await ctx.integrations.db.execute(
        `UPDATE deals SET updated_at = now() WHERE id = $1`,
        [target.deal_id],
        { label: "Bump deal updated_at" }
      );
    }

    return {
      found: staleRuns.length,
      resumed: target.id,
      outcome: result.status === "completed"
        ? `completed: ${target.module_id} for deal ${target.deal_id} (${result.failedChunks ?? 0} failed chunks)`
        : result.status === "in_progress"
          ? `in_progress: ${result.phase} (analysis ${result.progress.analysisCompleted}/${result.progress.analysisTotal})`
          : `failed: ${result.firstError ?? result.phase}`,
    };
  },
});
